name: Infrastructure Security Scan
on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.rs"
      - "**.md"
      - "Cargo.*"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**.rs"
      - "**.md"
      - "Cargo.*"

concurrency:
  group: bingot√†-kics-${{ github.ref }}
  cancel-in-progress: true

jobs:
  infra-security-scan:
    uses: notdodo/github-actions/.github/workflows/infra-security-scan.yml@2e84638563b65587b42ba8ab87ccdf1922c412dd
    # infra-scan-v0.0.0
