name: Rust CI

on:
  push:
    branches:
      - "main"
    paths:
      - "**.rs"
      - "Cargo.*"
      - .github/workflows/rust-ci.yml
  pull_request:
    branches:
      - "main"
    paths:
      - "**.rs"
      - "Cargo.*"
      - .github/workflows/rust-ci.yml

concurrency:
  group: bingot√†-rust-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rust-ci:
    uses: notdodo/github-actions/.github/workflows/rust-ci.yml@e778425d969309bb62ecb0d9fa89e12f54604436
    # rust-ci-v0.0.0
